# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Add command_timeout
command_timeout = 6000

# Only 3 colors are used in the prompt:
# - #3A405A for the background of OS & directory
#.            and the text of username
# - #AEC5EB for the background of username
# - #F0E7D8 for for OS & directory text
format = """
[\ue0b6](#3A405A)\
$os[\ue0b4](fg:#3A405A bg:#AEC5EB)\
$username[\ue0b4](fg:#AEC5EB bg:#3A405A)\
$directory[\ue0b4](fg:#3A405A)\
$git_branch$git_status[\ue0b4](fg:#3A405A)\
$all
"""

[os]
format = "[$symbol]($style)"
style = "fg:#F0E7D8 bg:#3A405A"
disabled = false

[os.symbols]
Macos = ""

[username]
style_user = "bold fg:#3A405A bg:#AEC5EB"
format = "[$user]($style)"
disabled = false
show_always = true
aliases = {"goprayogo" = "gama"}

[directory]
style = "fg:#F0E7D8 bg:#3A405A"
format = "[ $path]($style)"
truncate_to_repo = true

[git_branch]
format = """ on [\ue0b6](fg:#3A405A)[$symbol](fg:#F0E7D8 bg:#3A405A)\
[\ue0b4](fg:#3A405A bg:#AEC5EB)\
[ $branch](bold bg:#AEC5EB fg:#3A405A)[\ue0b4](fg:#AEC5EB bg:#3A405A)"""
disabled = false

[git_status]
style = "bold fg:#CE4257 bg:#3A405A"
format = """[ $all_status$ahead_behind]($style)"""

[character] 
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
format = "[$symbol$version]($style) "
